export function getProducts() {
  const products = {
    6000: {
      entity_id: "6000",
      sku: "62646NC",
      name: "NCredible Ncredible N2, OTE, BLK/GNTML Audio - 62646NC",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "149.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 200,
    },
    6001: {
      entity_id: "6001",
      sku: "62735NC",
      name: "NCredible Ncredible Play, WL EB RS/GLD Audio - 62735NC",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "89",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 100,
    },
    6002: {
      entity_id: "6002",
      sku: "22418VRP",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6003: {
      entity_id: "6003",
      sku: "6003",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6004: {
      entity_id: "6004",
      sku: "6004",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6005: {
      entity_id: "6005",
      sku: "6005",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6006: {
      entity_id: "6006",
      sku: "6006",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6007: {
      entity_id: "6007",
      sku: "6007",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6008: {
      entity_id: "6008",
      sku: "6008",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6009: {
      entity_id: "6009",
      sku: "6009",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6010: {
      entity_id: "6010",
      sku: "6010",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6011: {
      entity_id: "6011",
      sku: "6011",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6012: {
      entity_id: "6012",
      sku: "6012",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6013: {
      entity_id: "6013",
      sku: "6013",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6014: {
      entity_id: "6014",
      sku: "6014",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6015: {
      entity_id: "6015",
      sku: "6015",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6016: {
      entity_id: "6016",
      sku: "6016",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6017: {
      entity_id: "6017",
      sku: "6017",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6018: {
      entity_id: "6018",
      sku: "6018",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6019: {
      entity_id: "6019",
      sku: "6019",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6020: {
      entity_id: "6020",
      sku: "6020",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6021: {
      entity_id: "6021",
      sku: "6021",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6022: {
      entity_id: "6022",
      sku: "6022",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6023: {
      entity_id: "6023",
      sku: "6023",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6024: {
      entity_id: "6024",
      sku: "6024",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6025: {
      entity_id: "6025",
      sku: "6025",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6026: {
      entity_id: "6026",
      sku: "6026",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6027: {
      entity_id: "6027",
      sku: "6027",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6028: {
      entity_id: "6028",
      sku: "6028",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
    6029: {
      entity_id: "6029",
      sku: "6029",
      name: "Nimbus9 App Atwater Cirrus2 RoseClr Case for Apple Atwater - 22418VRP",
      thumbnail: "/6/2/62646NC.jpg",
      manufacturer: "399",
      color: "210",
      is_new_product: "0",
      price: "19.990000",
      product_url:
        "https://scp.demoproject.info/index.php/default/ncredible-ncredible-n2-ote-blk-gntml-audio-62646nc.html",
      image:
        "https://scp.demoproject.info/media/catalog/product/cache/a8ead6b2406289b7c07111b09703616e/6/2/62646NC.jpg",
      max_sale_qty: 10000,
      cids: ["414"],
      mkids: [],
      mdids: [],
      devicemake: [],
      devicemodel: [],
      qty: 10,
    },
  };

  return products;
}

export function getLocations() {
  const locations = {
    207: {
      firstname: "Shama",
      lastname: "Arige",
      street: ["14811 Lyons Road, Suite 100"],
      country_id: "US",
      region: {
        region: "Florida",
        region_code: "FL",
        region_id: 57,
      },
      region_id: "57",
      city: "Delray Beach",
      postcode: "33446",
      telephone: "5612237640",
      custom_attributes: {
        location_is: {
          attribute_code: "location_is",
          value: "1",
        },
        location_is_verified: {
          attribute_code: "location_is_verified",
          value: "1",
        },
        location_name: {
          attribute_code: "location_name",
          value: "Delray Beach - Delray Marketplace",
        },
        location_class: {
          attribute_code: "location_class",
          value: "A",
        },
        location_store_id: {
          attribute_code: "location_store_id",
          value: "937",
        },
        location_status: {
          attribute_code: "location_status",
          value: "1",
        },
        location_district: {
          attribute_code: "location_district",
          value: "FLD3",
        },
        location_region: {
          attribute_code: "location_region",
          value: "FLD3",
        },
      },
      id: "207",
    },
    208: {
      firstname: "Shama",
      lastname: "Arige",
      street: ["14811 Lyons Road, Suite 100"],
      country_id: "US",
      region: {
        region: "Florida",
        region_code: "FL",
        region_id: 57,
      },
      region_id: "57",
      city: "Delray Beach",
      postcode: "33446",
      telephone: "5612237640",
      custom_attributes: {
        location_is: {
          attribute_code: "location_is",
          value: "1",
        },
        location_is_verified: {
          attribute_code: "location_is_verified",
          value: "1",
        },
        location_name: {
          attribute_code: "location_name",
          value: "Delray Beach - Delray Marketplace",
        },
        location_class: {
          attribute_code: "location_class",
          value: "A",
        },
        location_store_id: {
          attribute_code: "location_store_id",
          value: "937",
        },
        location_status: {
          attribute_code: "location_status",
          value: "1",
        },
        location_district: {
          attribute_code: "location_district",
          value: "FLD3",
        },
        location_region: {
          attribute_code: "location_region",
          value: "FLD3",
        },
      },
      id: "208",
    },
    209: {
      firstname: "Shama",
      lastname: "Arige",
      street: ["14811 Lyons Road, Suite 100"],
      country_id: "US",
      region: {
        region: "Florida",
        region_code: "FL",
        region_id: 57,
      },
      region_id: "57",
      city: "Delray Beach",
      postcode: "33446",
      telephone: "5612237640",
      custom_attributes: {
        location_is: {
          attribute_code: "location_is",
          value: "1",
        },
        location_is_verified: {
          attribute_code: "location_is_verified",
          value: "1",
        },
        location_name: {
          attribute_code: "location_name",
          value: "Delray Beach - Delray Marketplace",
        },
        location_class: {
          attribute_code: "location_class",
          value: "A",
        },
        location_store_id: {
          attribute_code: "location_store_id",
          value: "937",
        },
        location_status: {
          attribute_code: "location_status",
          value: "1",
        },
        location_district: {
          attribute_code: "location_district",
          value: "FLD3",
        },
        location_region: {
          attribute_code: "location_region",
          value: "FLD3",
        },
      },
      id: "209",
    },
    210: {
      firstname: "Shama",
      lastname: "Arige",
      street: ["14811 Lyons Road, Suite 100"],
      country_id: "US",
      region: {
        region: "Florida",
        region_code: "FL",
        region_id: 57,
      },
      region_id: "57",
      city: "Delray Beach",
      postcode: "33446",
      telephone: "5612237640",
      custom_attributes: {
        location_is: {
          attribute_code: "location_is",
          value: "1",
        },
        location_is_verified: {
          attribute_code: "location_is_verified",
          value: "1",
        },
        location_name: {
          attribute_code: "location_name",
          value: "Delray Beach - Delray Marketplace",
        },
        location_class: {
          attribute_code: "location_class",
          value: "A",
        },
        location_store_id: {
          attribute_code: "location_store_id",
          value: "937",
        },
        location_status: {
          attribute_code: "location_status",
          value: "1",
        },
        location_district: {
          attribute_code: "location_district",
          value: "FLD3",
        },
        location_region: {
          attribute_code: "location_region",
          value: "FLD3",
        },
      },
      id: "210",
    },
    211: {
      firstname: "Shama",
      lastname: "Arige",
      street: ["14811 Lyons Road, Suite 100"],
      country_id: "US",
      region: {
        region: "Florida",
        region_code: "FL",
        region_id: 57,
      },
      region_id: "57",
      city: "Delray Beach",
      postcode: "33446",
      telephone: "5612237640",
      custom_attributes: {
        location_is: {
          attribute_code: "location_is",
          value: "1",
        },
        location_is_verified: {
          attribute_code: "location_is_verified",
          value: "1",
        },
        location_name: {
          attribute_code: "location_name",
          value: "Delray Beach - Delray Marketplace",
        },
        location_class: {
          attribute_code: "location_class",
          value: "A",
        },
        location_store_id: {
          attribute_code: "location_store_id",
          value: "937",
        },
        location_status: {
          attribute_code: "location_status",
          value: "1",
        },
        location_district: {
          attribute_code: "location_district",
          value: "FLD3",
        },
        location_region: {
          attribute_code: "location_region",
          value: "FLD3",
        },
      },
      id: "211",
    },
    212: {
      firstname: "Shama",
      lastname: "Arige",
      street: ["14811 Lyons Road, Suite 100"],
      country_id: "US",
      region: {
        region: "Florida",
        region_code: "FL",
        region_id: 57,
      },
      region_id: "57",
      city: "Delray Beach",
      postcode: "33446",
      telephone: "5612237640",
      custom_attributes: {
        location_is: {
          attribute_code: "location_is",
          value: "1",
        },
        location_is_verified: {
          attribute_code: "location_is_verified",
          value: "1",
        },
        location_name: {
          attribute_code: "location_name",
          value: "Delray Beach - Delray Marketplace",
        },
        location_class: {
          attribute_code: "location_class",
          value: "A",
        },
        location_store_id: {
          attribute_code: "location_store_id",
          value: "937",
        },
        location_status: {
          attribute_code: "location_status",
          value: "1",
        },
        location_district: {
          attribute_code: "location_district",
          value: "FLD3",
        },
        location_region: {
          attribute_code: "location_region",
          value: "FLD3",
        },
      },
      id: "212",
    },
  };

  return locations;
}

export function getProdLocQty() {
  const prodLocQty = {
    6000: {
      207: { qty: 5 },
      208: { qty: 2 },
    },
    6001: {
      208: { qty: 5 },
      211: { qty: 20 },
    },
    6002: {
      209: { qty: 8 },
      211: { qty: 5 },
      212: { qty: 3 },
    },
  };

  return prodLocQty;
}
